package view.ui;

import java.awt.Dimension;
import model.game.logic.GameLevel;
import model.game.objects.Birdie;
import view.ui.GameScreen;

/**
 * This is offered as a pattern for using a <code>CardPanel</code> layout as
 * well as getting it started. In the future a class like this should contain as
 * little as possible. For now we can simply use it as a starting point.
 *
 * @author dmr
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Constructs a new <code>CardWindow</code>. This relies on the tools in
     * NetBeans. If you want to know what <code>initComponents</code> does,
     * click the code-fold for the generated code. The positioning code is at
     * the end of the fold and uses a variety of layouts. You didn't notice
     * these if you used the graphical tools in NetBeans.
     */
    public MainWindow() {
        initComponents();
        //this.setPreferredSize(new Dimension(800,100));
    }

    /**
     * Creates a new <code>CardManger</code> for a specified display area and
     * adds cards to it. Note that the <code>addCard</code> message is sent to
     * the <code>CardManger</code>.
     *
     * TODO: Consider returning the instance of "CardManger"
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        ForceInput = new javax.swing.JTextField();
        LaunchButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ResetButton = new javax.swing.JButton();
        BallSelector = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        nameField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        LevelSelector = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        game = new GameScreen();
        jScrollPane4 = new javax.swing.JScrollPane();
        ScoreBoard = new javax.swing.JTextArea();
        scoreBtn = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 50));
        setResizable(false);

        ForceInput.setText("600");

        LaunchButton.setText("<html><b>Launch</b></html>");
        LaunchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaunchButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Force");

        ResetButton.setText("<html><b>New Game</b></html>");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        BallSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Red", "Blue", "Green", "Basketball", "Bowling ball", "Dodgeball", "Eyeball", "The moon" }));
        BallSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BallSelectorActionPerformed(evt);
            }
        });

        jLabel2.setText("Ball color");

        jLabel3.setText("Background color");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Red", "Blue", "Green" }));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setToolTipText("");

        jLabel4.setText("Name");

        LevelSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SAND", "STONE", "ICE", "GRASS" }));
        LevelSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LevelSelectorActionPerformed(evt);
            }
        });

        jLabel5.setText("Game Level");
        jLabel5.setToolTipText("");

        javax.swing.GroupLayout gameLayout = new javax.swing.GroupLayout(game);
        game.setLayout(gameLayout);
        gameLayout.setHorizontalGroup(
            gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        gameLayout.setVerticalGroup(
            gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );

        ScoreBoard.setColumns(20);
        ScoreBoard.setRows(5);
        jScrollPane4.setViewportView(ScoreBoard);

        scoreBtn.setText("ADD SCORE");
        scoreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(LaunchButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(ForceInput, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(273, 273, 273)
                        .addComponent(jLabel5)
                        .addGap(35, 35, 35)
                        .addComponent(LevelSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BallSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(scoreBtn)))
                        .addGap(81, 81, 81)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jScrollPane4)))
                .addContainerGap())
            .addComponent(game, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(game, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LaunchButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LevelSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(ForceInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scoreBtn)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BallSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LaunchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaunchButtonActionPerformed
        // TODO add your handling code here:
        String text = ForceInput.getText();
        int force = Integer.parseInt(text);
        GameScreen gs = (GameScreen) game; //(cm.getCards().get(cardDisplayArea.getVisibleChildNumber()));
        Birdie birdie = gs.getLevel().getSimulation().getBirdie();
        birdie.launch(force);
        gs.getLevel().addToStrokeCount();

    }//GEN-LAST:event_LaunchButtonActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        // TODO add your handling code here:
        String x = LevelSelector.getSelectedItem().toString();
        GameLevel.LevelType level = GameLevel.LevelType.valueOf(x);
        GameScreen gs = (GameScreen) game; //(cm.getCards().get(cardDisplayArea.getVisibleChildNumber()));
        gs.newLevel(800, level);
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void LevelSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LevelSelectorActionPerformed

    }//GEN-LAST:event_LevelSelectorActionPerformed

    private void scoreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreBtnActionPerformed
        // TODO add your handling code here:
        String name = nameField.getText();
        GameScreen gs = (GameScreen) game; //(cm.getCards().get(cardDisplayArea.getVisibleChildNumber()));
        int score = gs.getLevel().getStrokeCount();
        gs.getHsm().addScore(name, score);
        ScoreBoard.setText(gs.getHsm().getHighscoreString());
    }//GEN-LAST:event_scoreBtnActionPerformed

    private void BallSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BallSelectorActionPerformed
        // TODO add your handling code here:

        String x = BallSelector.getSelectedItem().toString();
        System.out.println(x);
        GameScreen gs = (GameScreen) game; //(cm.getCards().get(cardDisplayArea.getVisibleChildNumber()));
        Birdie birdie = gs.getLevel().getSimulation().getBirdie();

        switch (x) {

            case "Red":
                birdie.setTexture("/balls/Red.png");
                break;
            case "Blue":
                birdie.setTexture("/balls/Blue.png");
                break;
            case "Green":
                birdie.setTexture("/balls/Green.png");
                break;
            case "Basketball":
                birdie.setTexture("/balls/Basketball.png");
                break;
            case "Bowling ball":
                birdie.setTexture("/balls/Bowling ball.png");
                break;
            case "Dodgeball":
                birdie.setTexture("/balls/Dodgeball.png");
                break;
            case "Eyeball":
                birdie.setTexture("/balls/Eyeball.png");
                break;
            case "The moon":
                birdie.setTexture("/balls/The moon.png");
                break;
        }
    }//GEN-LAST:event_BallSelectorActionPerformed

    /**
     * Attempts to set the look-and-feel for the application. In this case it is
     * the laf named Nimbus. Press the code-fold to see what is happening. The
     * application is made runnable and made available to be run. From the
     * documentation:
     * <i>"EventQueue is a platform-independent class that queues events, both
     * from the underlying peer classes and from trusted application
     * classes."</i><br>
     * <i>"Causes runnable to have its run method called in the dispatch thread
     * of the system EventQueue. This will happen after all pending events are
     * processed."
     * </i><br> More on these two point later.
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BallSelector;
    private javax.swing.JTextField ForceInput;
    private javax.swing.JButton LaunchButton;
    private javax.swing.JComboBox<String> LevelSelector;
    private javax.swing.JButton ResetButton;
    private javax.swing.JTextArea ScoreBoard;
    private javax.swing.JPanel game;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton scoreBtn;
    // End of variables declaration//GEN-END:variables
}
