package cards;

import cardMgt.CardManager;
import guiActions.NextAction;

/**
 This class provides a card with a specific appearance and functionality.

 @author dmr
 */
public class Third extends Card {

/**
 Creates new instance of <code> Third</code> Third. The implementation details
 are very similar to the
 <code>First</code> class.

 TODO: Establish a clear style and format for the Card subclass javadocs

 @param cm as a <code>CardManger</code>
 @param name as a <code>String</code>
 */
public Third(CardManager cm, String name) {
    super(cm, name);
    initComponents();
}

/**
 This method is called from within the constructor to initialize the form.
 WARNING: Do NOT modify this code. The content of this method is always
 regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        testButtonCard = new javax.swing.JButton(new NextAction("managed next",cm.getManager()));
        ancestorButtonCard = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ancestorButtonTextDisplay = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 102));

        testButtonCard.setText("Back");

        ancestorButtonCard.setText("Ancestor");
        ancestorButtonCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ancestorButtonCardActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("This is the third card in the deck");

        ancestorButtonTextDisplay.setColumns(20);
        ancestorButtonTextDisplay.setLineWrap(true);
        ancestorButtonTextDisplay.setRows(5);
        ancestorButtonTextDisplay.setWrapStyleWord(true);
        jScrollPane1.setViewportView(ancestorButtonTextDisplay);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ancestorButtonCard)
                    .addComponent(testButtonCard))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(testButtonCard)
                        .addGap(18, 18, 18)
                        .addComponent(ancestorButtonCard))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

/**
 Gets and displays a text representation of the parent of this card.

 @param evt as an Action Event
 */
    private void ancestorButtonCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ancestorButtonCardActionPerformed
        StringBuilder sb = new StringBuilder();
        sb.append("This is ").append(this).append("the Parent of this is ").append(this.getParent());
        ancestorButtonTextDisplay.setText(sb.toString());
    }//GEN-LAST:event_ancestorButtonCardActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ancestorButtonCard;
    private javax.swing.JTextArea ancestorButtonTextDisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton testButtonCard;
    // End of variables declaration//GEN-END:variables
}
